apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: app-demo-evento-location
  description: Location to import all app-demo-evento catalog components
spec:
  targets:
    - ./.platform/*.yaml
